### ISSUE TITLE
Provide session support

### ISSUE THREAD

**Issue by dueckes** [MYOB-Technology/http_stub#5]
##### Background
Server state is currently shared by all clients.

##### Description
To better facilitate concurrent use, where each client has isolated state, support the concept of session.
Clients would need to change to accommodate retaining and providing a session ID.
This is somewhat controversial and has been avoided to date due to the leakage of session ID and the need for clients to change to accommodate the stub server.

Configurers would encapsulate the session ID when configuring the server, however, client source would need to provide the ID.

**Comment by dueckes** [comment]
To achieve concurrent tests in the absence of this, one approach I've used successfully is to start a number of stubs and pin tests to a stub.

**Comment by dueckes** [comment]
Session support will be possible via pinning a session to a parameter or header value.

```ruby
`stub_server.session_identifier = { header: :my_session_id }`
```

The above will associate all requests with the same `my_session_id` header value to a stub session.

The `http_stub` dashboard will be adjusted to allow administrators to navigate sessions and stubs, matches & misses within a session.

**Comment by dueckes** [comment]
Added within ce1ad1bc575548c1a77e21163744d4bf343b2e73

Note that a session is conceptually an isolated container for stubs.
When a session is created it initially contains the stubs that were enabled on server start-up.

Scenarios are accessible from any sessions.

When enabled through configuration of the `session_identifier`, a `session` can be interacted with via the Configurer DSL and has a similar API as the `stub_server`:
```ruby
session = stub_server.session("some session id")

session.add_stub! do |stub|
...
end

session.activate!("Some scenario)

session.reset! # Resets the sessions stubs to it's original state, which is any stubs enabled during server start-up

session.delete! # Deletes the session
```

**Comment by andykingking** [comment]
This is awesome!
